= My Project
firstname lastname
1.0.0, {docdate}: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/asciidoctor-docker-template] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Pflichtenheft

=== Ausgangssituation

Der Hype für Retro und Vintage ist so hoch wie nie zuvor. Es gibt viele Neueinsteiger und Interessierte,
die Schallplatten sammeln möchten oder bereits ein paar besitzen. Der Vinylumsatz in Österreich lag 2022 bei
10,6 Millionen Euro. In den USA, dem größten Vinylmarkt lag er bei 1,2 Mrd. US-Dollar.

https://www.wko.at/videos/lookaut/GStbmZU-z9Q/schallplatten-comeback-warum-vinyl-im-streaming-zeitalter-boomt[Daten lt. WKO]

=== Istzustand

Das Verwalten von großen Sammlung ist schwierig und verbraucht viel Zeit. Man findet oft seine Schallplatten nicht,
weiß nicht genau über den Wert oder die Größe der gesamten Sammlung Bescheid. Es besteht die Gefahr, Duplikate zu kaufen.

Es gibt zwar Software, die dieses Problem behandelt, aber selbst die neuesten Programme sind mindestens zehn Jahre alt.

=== Problemstellung

Man braucht ein zuverlässiges System um seine Schallplatten zu organisieren und verwalten. Es gilt eine Lösung
zu finden für das physische als auch software Seite des systems, da das Verwalten der Schallplatten mit einer reinen
Software Lösung nicht effective möglich ist.

=== Aufgabenstellung

==== Funktionale Anforderungen

    Katalogisierung: Optionale manuelle Eingabe oder Import von Metadaten.

    Barcode-Scanner: Kamera-Funktion zum Scannen des EAN/UPC-Codes auf dem Cover zur automatischen Datenerfassung.

    Standort-Management: Zuweisung eines physischen Lagerortes (z. B. "Regal A, Fach 3") für jede Platte.

    Sammlungs-Statistik: Dashboard mit Visualisierung des Gesamtwerts (via API-Anbindung, z.B. Discogs), Genre-Verteilung und Anzahl der Platten.

    Wunschliste & Dubletten-Check: Warnsystem beim Hinzufügen von Platten, die bereits vorhanden sind; Führen einer "Wantlist".

    Such- und Filterfunktion: Schnelles Finden von Alben nach verschiedenen Kriterien.

https://www.vinylherstellung.de/ean-label-code/[EAN/UPC - Codes]

==== Nichtfunktionale Anforderungen (NFA)

    Benutzbarkeit: Das Interface muss modern, minimalistisch und intuitiv bedienbar sein.

    Performance: Die Suche in einer Sammlung von bis zu 5.000 Datensätzen muss unter 200ms dauern.

    Offline-Fähigkeit: Die Basis-Suche muss auch ohne Internetverbindung (z.B. im Keller, ...) funktionieren.

=== Ziele [Wirkung]

    Effizienz: Die Zeit für das Suchen einer bestimmten Platte im physischen Archiv soll erheblich reduziert werden.

    Finanzielle Übersicht: Der Nutzer hat einen Überblick über den Marktwert seiner Investition.

    Fehlkauf-Vermeidung: Senkung der Fehlkäufe (Dubletten).

    Community-Anschluss: Vorbereitung für den Export/Teilen der Sammlung mit Gleichgesinnten.

=== Rahmenbedingungen

    Schnittstellen: Nutzung der Discogs-API zur Abfrage von Metadaten und Marktpreisen. (Max. 60 req pro Minute)

    Zeitplan: Ein Prototyp (MVP) muss innerhalb von 3 Monaten einsatzbereit sein.


== Entwurf "Wie mache ich es"
=== Systemarchitektur
=== ...

== Projekthandbuch "Organisatorische Rahmenbedingungen"



=== GANTT-Diagramm

mit User-Stories (definiert in YouTrack)

[plantuml,gantt-protoype,png]
----
@startgantt
[Test prototype] lasts 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] lasts 12 days
[Setup assembly line] starts at [Test prototype]'s end
[Test prototype 2] lasts 3 days
[Test prototype 2] starts at [Prototype completed]'s end
@endgantt
----

* link:minutes-of-meeting.html[Protokollvorlage]
* link:demo.html[Demo]

